"""Generate the verified Android UI-LOD0 -> world-LOD1 relation table.

The source catalog supplies the UI component path and identity.  The archived
Android character catalog supplies the independently observed LOD1 mesh name.
Rows are emitted only when both identities exist; index counts remain unknown
unless a future runtime probe records them, so the runtime still checks the
live object and its arrays before applying a row.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

SNAPSHOT = "2954fa80-23c1-1579-2b22-4ecfd6d70418"


def cpp(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", type=Path, default=Path(__file__).resolve().parents[2])
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    repo = args.repo
    output = args.output or repo / "native/modules/custom_model/android_lod_relations.generated.h"
    android_path = repo / "legacy/better-endfield-2.3.1/references/source-research/character-catalog/characters.json"
    android = {x["characterId"]: x for x in json.loads(android_path.read_text(encoding="utf-8"))["characters"]}
    rows: list[tuple[str, str, str, str, str, str, str]] = []
    for catalog_path in sorted((repo / "tools/CustomModel/catalog").glob("chr_*.json")):
        catalog = json.loads(catalog_path.read_text(encoding="utf-8"))
        character = catalog["character_id"]
        android_character = android.get(character)
        if not android_character:
            continue
        lod1 = {}
        for asset in android_character.get("modelAssets", []):
            path = asset.get("path", "")
            if "_lod1" not in path.lower():
                continue
            name = path.rsplit("##", 1)[1] if "##" in path else Path(path).stem
            canonical = name[:-2] if name.endswith("_8") else name[:-3] if name.endswith("_20") else name
            key = canonical.casefold()
            previous = lod1.get(key)
            if previous is None or name.endswith(("_8", "_20")):
                lod1[key] = name
        for component_id in sorted(catalog["components"], key=int):
            component = catalog["components"][component_id]
            source_mesh = component["mesh_name"]
            source_base = source_mesh[:-3] if source_mesh.endswith("_20") else source_mesh[:-2] if source_mesh.endswith("_8") else source_mesh
            target_mesh_guess = source_base.rsplit("_lod0", 1)[0] + "_lod1"
            observed_mesh = lod1.get(target_mesh_guess.casefold())
            target_mesh = None
            if observed_mesh:
                # Preserve the catalog's canonical casing while retaining an
                # independently observed Android suffix such as _8.
                suffix = "_8" if observed_mesh.endswith("_8") else "_20" if observed_mesh.endswith("_20") else ""
                target_mesh = target_mesh_guess + suffix
            observations = component.get("evidence", {}).get("observations", {})
            ui = next((x for name, x in observations.items() if name.endswith("_uimodel") and x.get("path")), None)
            if not target_mesh or not ui:
                continue
            source_path = ui["path"].split("/", 1)[1]
            target_renderer = target_mesh[:-2] if target_mesh.endswith("_8") else target_mesh[:-3] if target_mesh.endswith("_20") else target_mesh
            target_path = "Mesh_all/lod1/" + target_renderer
            rows.append((character, catalog["ui_resource"], catalog["world_resource"], source_path,
                         source_mesh, target_path, target_mesh))
    rows.sort()
    lines = ["#pragma once", "// Generated by tools/CustomModel/generate_android_lod_relations.py.",
             "// Android manifest snapshot: " + SNAPSHOT, "namespace BetterEndfield::CustomModel {",
             "inline std::span<const GenericMatching::ExactLodRelation> AndroidLodRelations() {",
             "    static const GenericMatching::ExactLodRelation rows[] = {"]
    for character, source_resource, target_resource, source_path, source_mesh, target_path, target_mesh in rows:
        lines.append("        {{" + cpp("Android") + "," + cpp(SNAPSHOT) + "}," +
                     ",".join(map(cpp, (character, source_resource, target_resource, source_path,
                                          source_mesh, target_path, target_mesh))) + ",true,true,0,false},")
    lines += ["    };", "    return rows;", "}",
              "inline GenericMatching::AssetScope AndroidLodAssetScope() {",
              "    return {\"Android\",\"" + SNAPSHOT + "\"};", "}", "}", ""]
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")
    print(f"generated {len(rows)} Android LOD relations -> {output}")


if __name__ == "__main__":
    main()
