<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <AssemblyName>EFStartChange</AssemblyName>
    <RootNamespace>EFStartChange.UI</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <UseWinUI>true</UseWinUI>
    <WindowsPackageType>None</WindowsPackageType>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <PublishSingleFile>false</PublishSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK.WinUI" Version="1.8.260709004" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource
      Include="Assets\character-presets.json"
      LogicalName="EFStartChange.UI.Assets.character-presets.json" />
  </ItemGroup>

  <Target Name="CopyWinUIResourcesToPublish" AfterTargets="Publish">
    <ItemGroup>
      <WinUICompiledResource Include="$(TargetDir)*.xbf" />
      <WinUICompiledResource Include="$(TargetDir)$(AssemblyName).pri" />
    </ItemGroup>
    <Copy
      SourceFiles="@(WinUICompiledResource)"
      DestinationFolder="$(PublishDir)"
      SkipUnchangedFiles="true" />
  </Target>
</Project>
