<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../BetterEndfieldNext.UI/Services/BemRuntimeSettings.cs" Link="BemRuntimeSettings.cs" />
    <Compile Include="../../BetterEndfieldNext.UI/Services/HotkeyService.cs" Link="HotkeyService.cs" />
    <Compile Include="../../BetterEndfieldNext.UI/Services/BemPackageService.cs" Link="BemPackageService.cs" />
    <Compile Include="../../BetterEndfieldNext.UI/Services/BemToolService.cs" Link="BemToolService.cs" />
  </ItemGroup>
</Project>
