#!/usr/bin/env python3
"""Refresh compact combat-overlay portraits from the CEP character index."""

from __future__ import annotations

import html as html_module
import io
import json
import re
import urllib.request
from pathlib import Path

from PIL import Image, ImageOps


ROOT = Path(__file__).resolve().parents[1]
INDEX_URL = "https://end.canmoe.com/zh-CN/wiki/characters"
ASSET_DIR = ROOT / "native" / "modules" / "combat_stats" / "assets" / "avatars"
OVERLAY_DIR = ROOT / "native" / "modules" / "combat_stats" / "overlay"

CARD_PATTERN = re.compile(
    r'href="/zh-CN/wiki/characters/(?P<id>chr_[^"]+)"[\s\S]*?'
    r'data-testid="rarity-frame-image"[\s\S]*?src="(?P<src>/images/characters/[^"]+)"'
    r'[\s\S]*?<h3[^>]*>(?P<name>[^<]+)</h3>'
)


def download(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": "BetterEndfield/2.1"})
    with urllib.request.urlopen(request, timeout=30) as response:
        return response.read()


def cpp_wstring(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def main() -> None:
    page = download(INDEX_URL).decode("utf-8")
    records: list[dict[str, object]] = []
    seen: set[str] = set()
    for match in CARD_PATTERN.finditer(page):
        character_id = match.group("id")
        if character_id in seen:
            continue
        seen.add(character_id)
        source = html_module.unescape(match.group("src"))
        name = html_module.unescape(match.group("name"))
        records.append({"id": character_id, "name": name, "source": source})

    if len(records) < 25:
        raise RuntimeError(f"Character index yielded only {len(records)} records")

    ASSET_DIR.mkdir(parents=True, exist_ok=True)
    OVERLAY_DIR.mkdir(parents=True, exist_ok=True)
    for index, record in enumerate(records):
        source_url = "https://end.canmoe.com" + str(record["source"])
        source_bytes = download(source_url)
        with Image.open(io.BytesIO(source_bytes)) as source_image:
            portrait = ImageOps.fit(
                source_image.convert("RGBA"),
                (112, 112),
                method=Image.Resampling.LANCZOS,
                centering=(0.5, 0.35),
            )
            output_path = ASSET_DIR / f"{record['id']}.png"
            portrait.save(output_path, format="PNG", optimize=True)
        record["resourceId"] = 1000 + index
        record["sourceUrl"] = source_url

    header_lines = [
        "// Generated by scripts/UpdateCombatAvatars.py. Do not edit by hand.",
        "#pragma once",
        "",
        "struct CharacterAsset {",
        "    const char* id;",
        "    const wchar_t* name;",
        "    int resource_id;",
        "};",
        "",
        "inline constexpr CharacterAsset kCharacterAssets[] = {",
    ]
    rc_lines = ["// Generated by scripts/UpdateCombatAvatars.py."]
    for record in records:
        header_lines.append(
            f'    {{"{record["id"]}", L"{cpp_wstring(str(record["name"]))}", '
            f'{record["resourceId"]}}},'
        )
        rc_lines.append(
            f'{record["resourceId"]} PNG "../assets/avatars/{record["id"]}.png"'
        )
    header_lines.extend(["};", ""])

    (OVERLAY_DIR / "character_assets.generated.h").write_text(
        "\n".join(header_lines), encoding="utf-8", newline="\n"
    )
    (OVERLAY_DIR / "avatars.generated.rcinc").write_text(
        "\n".join(rc_lines) + "\n", encoding="utf-8", newline="\n"
    )
    manifest = {
        "schemaVersion": 1,
        "source": INDEX_URL,
        "characters": records,
    }
    (ASSET_DIR.parent / "characters.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    print(f"Updated {len(records)} combat portraits in {ASSET_DIR}")


if __name__ == "__main__":
    main()
