<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../../ui/BetterEndfield.UI/Services/BemPackageService.cs" Link="BemPackageService.cs" />
    <Compile Include="../../../ui/BetterEndfield.UI/Services/BemReportPresentation.cs" Link="BemReportPresentation.cs" />
  </ItemGroup>
</Project>
