// Generated by scripts/UpdateCombatAvatars.py. Do not edit by hand.
#pragma once

struct CharacterAsset {
    const char* id;
    const wchar_t* name;
    int resource_id;
};

inline constexpr CharacterAsset kCharacterAssets[] = {
    {"chr_0025_ardelia", L"艾尔黛拉", 1000},
    {"chr_0026_lastrite", L"别礼", 1001},
    {"chr_9000_endmin", L"管理员", 1002},
    {"chr_0013_aglina", L"洁尔佩塔", 1003},
    {"chr_0032_lizhiyan", L"诀", 1004},
    {"chr_0029_pograni", L"骏卫", 1005},
    {"chr_0033_camille", L"卡缪", 1006},
    {"chr_0016_laevat", L"莱万汀", 1007},
    {"chr_0035_liino", L"梨诺", 1008},
    {"chr_0015_lifeng", L"黎风", 1009},
    {"chr_0028_wulfa", L"洛茜", 1010},
    {"chr_0031_mifu", L"弭弗", 1011},
    {"chr_0027_tangtang", L"汤汤", 1012},
    {"chr_0017_yvonne", L"伊冯", 1013},
    {"chr_0009_azrila", L"余烬", 1014},
    {"chr_0030_zhuangfy", L"庄方宜", 1015},
    {"chr_0024_deepfin", L"阿列什", 1016},
    {"chr_0012_avywen", L"艾维文娜", 1017},
    {"chr_0005_chen", L"陈千语", 1018},
    {"chr_0018_dapan", L"大潘", 1019},
    {"chr_0007_ikut", L"弧光", 1020},
    {"chr_0006_wolfgd", L"狼卫", 1021},
    {"chr_0004_pelica", L"佩丽卡", 1022},
    {"chr_0011_seraph", L"赛希", 1023},
    {"chr_0014_aurora", L"昼雪", 1024},
    {"chr_0021_whiten", L"埃特拉", 1025},
    {"chr_0023_antal", L"安塔尔", 1026},
    {"chr_0020_meurs", L"卡契尔", 1027},
    {"chr_0019_karin", L"秋栗", 1028},
    {"chr_0022_bounda", L"萤石", 1029},
};
