#!/usr/bin/env python3
"""Buff resource table builder.

A local development tool, in two halves:

    1. --emit-id-list <dir>
       Writes combat-buff-ids.txt next to BetterEndfield.BuffProbe.dll. The ids
       are just the BuffData filenames; the contents are MemoryPack blobs with a
       .json suffix and cannot be read here.

    2. default
       Consumes the probe's combat-buffs.json and writes the two static tables
       the web build ships, so buff mechanics stop riding along in every record.

Two tables, split on whether a buff touches damage at all. A buff with no
attribute, damage, heal, poise, global or shield entry is a marker, a spawn
flag, a VFX carrier or an AI state -- the bulk of what shows up as
contributionKind "other". Those are real, and the timeline still names them, so
they are not dropped; they just move to the lazily loaded half.

Rows are keyed by the append-only id registry index rather than by the buff id
string. The registry already carries all 2,872 ids because snapshots reference
them, so repeating the strings here would cost about 100 KB of bundle for
nothing, and the index is what a BEC snapshot names a buff by anyway.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

TABLE_VERSION = 1


def default_probe_output() -> Path:
    root = os.environ.get("LOCALAPPDATA")
    base = Path(root) if root else Path.home()
    return base / "BetterEndfield" / "combat-buffs.json"


def emit_id_list(buff_data_dir: Path, destination: Path) -> int:
    if not buff_data_dir.is_dir():
        raise SystemExit(f"BuffData directory not found: {buff_data_dir}")
    ids = sorted(path.stem for path in buff_data_dir.glob("*.json"))
    # A destination that does not name the file itself is taken as the probe's
    # directory, which usually does not exist yet.
    target = destination if destination.suffix == ".txt" else destination / "combat-buff-ids.txt"
    target.parent.mkdir(parents=True, exist_ok=True)
    with open(target, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("# Generated by build_buff_table.py --emit-id-list\n")
        for value in ids:
            handle.write(value + "\n")
    print(f"[+] {len(ids)} buff ids -> {target}")
    return len(ids)


def default_vfs_path() -> Optional[Path]:
    configured = os.environ.get("ENDFIELD_VFS")
    for candidate in (Path(configured) if configured else None,
                      Path("E:/Endfield Game/Endfield_Data/StreamingAssets")):
        if candidate and candidate.exists():
            return candidate
    return None


def export_buff_icons(sprites: Set[str], cache_dir: Path, output_dir: Path,
                      vfs_path: Optional[Path], extractor: Path, threads: int) -> None:
    """Copy the buff sprites the tables reference into the web bundle.

    The cache is shared with export_combat_data.py and already holds most of
    these: buff icons overlap the skill families it extracts. Only the genuine
    gaps are pulled from the game, because a VFS scan costs minutes.
    """
    try:
        from PIL import Image
    except ImportError as error:
        raise SystemExit("Pillow is required for icon export: pip install Pillow") from error

    cache_dir.mkdir(parents=True, exist_ok=True)
    cached = {path.stem.lower(): path for path in cache_dir.rglob("*.png")}
    absent = {name for name in sprites if name.lower() not in cached}
    if absent:
        if not vfs_path:
            raise SystemExit("Endfield StreamingAssets not found; pass --vfs or set ENDFIELD_VFS")
        if not extractor.exists():
            raise SystemExit(f"texture extractor not found: {extractor}")
        print(f"[*] {len(absent)} of {len(sprites)} buff sprites are not cached; extracting")
        # Enumerate exactly what is missing instead of guessing a family prefix.
        # Buff sprites do not share one: alongside icon_battle_* they include
        # icon_energy_*, icon_laevat_*, icon_shadow_*, icon_infliction_* and bare
        # names like `airborne`. A family regex extracted the wrong 100 and left
        # all 21 gaps, at three and a half minutes a run.
        pattern = "^(?:" + "|".join(sorted(re.escape(name) for name in absent)) + ")$"
        subprocess.run([
            str(extractor), "extract",
            "--vfs", str(vfs_path),
            "--out", str(cache_dir),
            "--asset-name", pattern,
            "--types", "Texture2D",
            "--threads", str(max(1, threads)),
            "--format", "png",
            "--png-compression", "fast",
            "--max-memory-gb", "16",
            "--exclude-material",
            "--skip-missing",
        ], check=True)
        cached = {path.stem.lower(): path for path in cache_dir.rglob("*.png")}

    output_dir.mkdir(parents=True, exist_ok=True)
    expected = {f"{name}.png".lower() for name in sprites}
    for stale in output_dir.glob("*.png"):
        if stale.name.lower() not in expected:
            stale.unlink()

    copied, missing = 0, []
    for name in sorted(sprites):
        source = cached.get(name.lower())
        if not source:
            missing.append(name)
            continue
        with Image.open(source) as original:
            image = original.convert("RGBA")
            image.thumbnail((128, 128), Image.Resampling.LANCZOS)
            image.save(output_dir / f"{name}.png", format="PNG", optimize=True, compress_level=9)
        copied += 1
    print(f"[+] buff icons: {copied}/{len(sprites)} -> {output_dir}")
    if missing:
        print(f"[!] {len(missing)} sprites are not in the game assets: {missing[:5]}")


def load_registry(path: Path) -> Dict[str, int]:
    if not path.exists():
        raise SystemExit(f"id registry not found: {path} (run export_combat_data.py first)")
    with open(path, "r", encoding="utf-8") as handle:
        payload = json.load(handle)
    return {value: index for index, value in enumerate(payload.get("ids") or [])}


def blackboard(value: Any) -> Optional[Any]:
    """A BlackboardDouble is a literal or a runtime key; only the literal is static."""
    if not isinstance(value, dict):
        return None
    if "v" in value:
        number = value["v"]
        if number is None:
            return None
        rounded = round(float(number), 6)
        return int(rounded) if rounded == int(rounded) else rounded
    key = value.get("k")
    return {"k": key} if key else None


def compact_attributes(entry: Any) -> List[List[Any]]:
    """[modifyAttributeType, attributeType, formulaItem, param] per modifier."""
    if not isinstance(entry, dict):
        return []
    out: List[List[Any]] = []
    for modifier in entry.get("m") or []:
        param = blackboard(modifier.get("p"))
        if param is None:
            continue
        out.append([modifier.get("mt", 0), modifier.get("at", 0),
                    modifier.get("fi", 0), param])
    return out


def compact_damage(entries: Any) -> List[List[Any]]:
    """[enableSide, side, zoneName, addition] per zone write."""
    out: List[List[Any]] = []
    for data in entries or []:
        enable_side = data.get("side", 0)
        for zone in data.get("zones") or []:
            addition = blackboard(zone.get("add"))
            name = zone.get("zone") or ""
            if addition is None or not name:
                continue
            out.append([enable_side, zone.get("side", 0), name, addition])
    return out


def sprite_name(path: str) -> str:
    """Only the leaf matters; the directory prefix is identical for every icon."""
    if not path:
        return ""
    return path.replace("\\", "/").rsplit("/", 1)[-1].rsplit(".", 1)[0]


def compact_buff(raw: Dict[str, Any]) -> Tuple[Dict[str, Any], bool]:
    attributes = compact_attributes(raw.get("attr"))
    damage = compact_damage(raw.get("dmg"))
    counts = (int(raw.get("heal") or 0), int(raw.get("poise") or 0),
              int(raw.get("global") or 0), int(raw.get("shield") or 0))
    stacking = raw.get("stacking") or {}

    row: Dict[str, Any] = {}
    icon = sprite_name(raw.get("icon") or "")
    if icon:
        row["ic"] = icon
    if raw.get("hasIcon"):
        row["hi"] = 1
    if attributes:
        row["at"] = attributes
    if damage:
        row["dz"] = damage
    if any(counts):
        row["c"] = list(counts)
    tags = [tag.get("n") or str(tag.get("id")) for tag in raw.get("tags") or []]
    if tags:
        row["tg"] = tags
    if raw.get("lifeType"):
        row["lt"] = raw["lifeType"]
    duration = blackboard(raw.get("duration"))
    if duration is not None:
        row["d"] = duration
    interval = blackboard(raw.get("triggerInterval"))
    if interval is not None:
        row["ti"] = interval
    if raw.get("waitFirstTrigger"):
        row["wf"] = 1
    trigger_count = blackboard(raw.get("maxTrigger"))
    if trigger_count is not None:
        row["mt"] = trigger_count
    if stacking:
        # identifierType, stackingType, maxStackCnt, stackingKey, maxStackCntKey
        entry: List[Any] = [stacking.get("idType", 0), stacking.get("type", 0),
                            stacking.get("maxCount", 0)]
        key = stacking.get("key") or ""
        max_key = stacking.get("maxKey") or "" if stacking.get("useMaxKey") else ""
        if key or max_key:
            entry.append(key)
        if max_key:
            entry.append(max_key)
        row["st"] = entry
    dispel = raw.get("dispel") or {}
    if dispel.get("can"):
        row["dp"] = dispel.get("level", 0)

    mechanical = bool(attributes or damage or any(counts))
    return row, mechanical


def build(probe_path: Path, registry_path: Path, main_output: Path,
          full_output: Path, icons: Optional[Dict[str, Any]] = None) -> None:
    if not probe_path.exists():
        raise SystemExit(
            f"probe output not found: {probe_path}\n"
            "Build BetterEndfield.BuffProbe, inject it, enter a battle and press its hotkey."
        )
    with open(probe_path, "r", encoding="utf-8") as handle:
        payload = json.load(handle)
    buffs = payload.get("buffs") or []
    if not buffs:
        raise SystemExit("probe output carries no buffs")
    missing = payload.get("missing") or []
    print(f"[*] probe: requested={payload.get('requested')} exported={payload.get('exported')} "
          f"missingSample={len(missing)}")

    registry = load_registry(registry_path)
    main_rows: Dict[str, Any] = {}
    full_rows: Dict[str, Any] = {}
    unregistered: List[str] = []
    for raw in buffs:
        buff_id = raw.get("id") or ""
        index = registry.get(buff_id)
        if index is None:
            unregistered.append(buff_id)
            continue
        row, mechanical = compact_buff(raw)
        if not row:
            continue
        (main_rows if mechanical else full_rows)[str(index)] = row

    for path, rows, label in ((main_output, main_rows, "mechanical"),
                              (full_output, full_rows, "remaining")):
        path.parent.mkdir(parents=True, exist_ok=True)
        table = {"tableVersion": TABLE_VERSION, "idv": len(registry), "b": rows}
        with open(path, "w", encoding="utf-8") as handle:
            json.dump(table, handle, ensure_ascii=False, separators=(",", ":"))
        print(f"[+] {label}: {len(rows)} buffs -> {path} "
              f"({path.stat().st_size / 1024:.1f} KB)")

    if icons is not None:
        sprites = {row["ic"] for rows in (main_rows, full_rows)
                   for row in rows.values() if row.get("ic")}
        export_buff_icons(sprites, **icons)

    if unregistered:
        print(f"[!] {len(unregistered)} buff ids are not in the id registry "
              f"(re-run export_combat_data.py): {unregistered[:5]}")
    if missing:
        print(f"[!] the client could not load {len(missing)} of the requested ids "
              f"(first few): {missing[:5]}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--emit-id-list", type=Path, metavar="DEST",
                        help="write combat-buff-ids.txt for the probe and exit")
    parser.add_argument("--buff-data", type=Path,
                        default=Path("research/combat-jsondata/Data/Json/BuffData"),
                        help="BuffData directory; only the filenames are read")
    parser.add_argument("--probe-output", type=Path, default=default_probe_output(),
                        help="combat-buffs.json written by BetterEndfield.BuffProbe")
    parser.add_argument("--id-registry", type=Path,
                        default=Path("tools/CombatDataExporter/id_registry.json"))
    parser.add_argument("--output", type=Path,
                        default=Path("web/src/data/combat-buffs.min.json"),
                        help="table shipped with the main bundle")
    parser.add_argument("--full-output", type=Path,
                        default=Path("web/src/data/combat-buffs-full.min.json"),
                        help="table loaded on demand")
    parser.add_argument("--export-icons", action="store_true",
                        help="also copy the referenced buff sprites into the web bundle")
    parser.add_argument("--icon-output", type=Path,
                        default=Path("web/public/icons/buffs"))
    parser.add_argument("--icon-cache", type=Path,
                        default=Path("tools/CombatDataExporter/.icon-cache"),
                        help="shared with export_combat_data.py")
    parser.add_argument("--vfs", type=Path, default=default_vfs_path(),
                        help="Endfield_Data/StreamingAssets (or set ENDFIELD_VFS)")
    parser.add_argument("--image-extractor", type=Path,
                        default=Path("tools/EndfieldStudio/AnimeStudio.Endfield.Cli"
                                     "/bin/Release/net9.0/endfield-dump.exe"))
    parser.add_argument("--icon-threads", type=int, default=min(os.cpu_count() or 1, 16))
    args = parser.parse_args()

    if args.emit_id_list is not None:
        emit_id_list(args.buff_data, args.emit_id_list)
        return
    icons = {
        "cache_dir": args.icon_cache,
        "output_dir": args.icon_output,
        "vfs_path": args.vfs,
        "extractor": args.image_extractor,
        "threads": args.icon_threads,
    } if args.export_icons else None
    build(args.probe_output, args.id_registry, args.output, args.full_output, icons)


if __name__ == "__main__":
    main()
